# Generated by Django 5.0.6 on 2025-10-28 21:50

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Действие, которое необходимо выполнить.",
                max_length=255,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Указывает, является ли привычка приятной.",
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Если истина, привычка видна другим пользователям.",
                verbose_name="Публичная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Как часто выполняется привычка (от 1 до 7 дней).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="Периодичность (в днях)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True,
                help_text="Место, где выполняется привычка.",
                max_length=255,
                null=True,
                verbose_name="Место",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Приятная привычка, связанная с выполнением основной привычки.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Чем пользователь себя вознаградит за выполнение привычки.",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Время, когда нужно выполнять привычку.",
                verbose_name="Время выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.DurationField(
                default=datetime.timedelta(seconds=120),
                help_text="Предполагаемое время на выполнение привычки (до 120 секунд).",
                verbose_name="Время на выполнение",
            ),
        ),
    ]
